### ISSUE TITLE
Could you teach me how to use other template engine?

### ISSUE THREAD

**Issue by circle8z** [ice/framework#104]
As a countermeasure for XSS, I want to use "[autoescape](http://twig.sensiolabs.org/doc/tags/autoescape.html)" of "[Twig](https://github.com/twigphp/Twig)".

**Comment by mruz** [comment]
I added Twig template engine into https://github.com/ice/base/pull/45. To use twig add:

`composer.json`

``` json
"twig/twig": ">=1.24.0"
```

`app/boot/Base.php`

``` php
$twig = new Twig($view, $this->di, [
    'cache' => __ROOT__ . '/app/tmp/twig/',
    'auto_reload' => true
]);

$view->setEngines([
    '.md' => 'App\Libraries\Markdown',
    '.sleet' => $sleet,
    '.twig' => $twig,
    '.phtml' => 'Ice\Mvc\View\Engine\Php'
]);
```

Run `composer update` and create some view with `.twig` extension.

**Comment by circle8z** [comment]
I have just confirmed Twig template in [ice/base](https://github.com/ice/base).
Thank you very much!
