### ISSUE TITLE
Will Ice framework support PHP7 soon?

### ISSUE THREAD

**Issue by circle8z** [ice/framework#111]
http://phalcon.io/phalconphp-and-php7

**Comment by mruz** [comment]
There is build/PHP7 folder and ice is compiling now, but I didn't check if all works.

**Comment by circle8z** [comment]
I see. Thanks for your reply.

**Comment by mruz** [comment]
Could you try Ice 1.1.3 and PHP7?

**Comment by madoka8** [comment]
I have just confirmed Ice 1.1.3 and PHP7.
Thank you very much!

**Comment by kcloze** [comment]
On my mac os,I use ice with PHP7,do good job!

**Comment by circle8z** [comment]
I have just added the following issue.
https://github.com/ice/base/issues/48

```
PHP7.0.7
Ice 1.1.4
```
