### ISSUE TITLE
[SOLVED] wamp server

### ISSUE THREAD

**Issue by The-Hasanov** [ice/framework#112]
how add extension on wampserver ?

**Comment by mruz** [comment]
I didn't try on wamp (just xampp and wpn-xm), but you need to copy `php_ice.dll` into `C:\wamp\bin\php\php5.6.X\ext`, append at the end of the `C:\wamp\bin\php\php5.6.X\php.ini` file: `extension=php_ice.dll` and restart the server.

**Comment by The-Hasanov** [comment]
php error log
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:/wamp64/bin/php/php5.6.16/ext/php_ice.dll' - The specified module could not be found.

 in Unknown on line 0
phalcon work correctly

Compiler  MSVC11 (Visual C++ 2012)  
Architecture  x64  
ice 1.1.2 x64

**Comment by mruz** [comment]
Wamp only comes with php TS, but I compiled Ice with NTS. You can [compile](http://www.iceframework.org/doc/introduction/windows) ice without `--disable-zts` or try to add php NTS version to wamp (but you need to change `php5_module` to [fcgid_module](https://www.apachelounge.com/download/) and reconfigure apache).

I'd recommend [wpn-xm](http://wpn-xm.org/) with nginx and php-fpm module.

**Comment by mruz** [comment]
I also compiled Ice extension (php 5.6 TS x64) for you/wamp [ice-1.1.2-php-5.6-ts-vc11-x64.zip](https://github.com/ice/framework/files/231339/ice-1.1.2-php-5.6-ts-vc11-x64.zip).

**Comment by mruz** [comment]
I added dlls to [download](http://www.iceframework.org/info/download#windows) section. If you want, you could try the php7 version.
