### ISSUE TITLE
What different of other frameworks?

### ISSUE THREAD

**Issue by mcddx330** [ice/framework#114]
Hello.

I'm finding some PHP7 frameworks and see some benchmark pages.
This framework looks like so fast. amazing. but I don't know other features...

So what key points of this framework? now I'm planning use to lumen because I'll make not too big product.

**Comment by mruz** [comment]
Hi,
Thanks for your interest!

Ice really is quite different compared to the other frameworks; it isn’t just another package that you download, rather it’s a PHP module written in C like [Phalcon](https://github.com/phalcon/cphalcon), so you need to [download](http://www.iceframework.org/info/download) a binary package for your platform or compile it from source code. It's similar to Phalcon #62, but more light. The advantage is speed, the downside is that not everything is [documented](http://www.iceframework.org/doc), but you have the [api](http://doc.iceframework.org/latest/).

I encourage you to try it ;)

**Comment by mcddx330** [comment]
Thank you reply! 

Now I trying ice and read the doc, but routing doesn't work. (always show index page on [hello](https://github.com/ice/hello)).
I using [h2o](https://github.com/h2o/h2o) and rewrite is working on lumen.
I'll use this framework if it's work cause so fast and easy to write.
So what can i do this problem? or ice isn't work on h2o?

**Comment by mruz** [comment]
You need to add rewrite rule (mruby? https://github.com/h2o/h2o/issues/740):

Example for nginx:

``` nginx
rewrite ^/(.*)$ /index.php?_url=/$1;
```

For apache:

``` apache
RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]
```

or set base uri `/index.php?_url=/` in the `App/Bootstrap.php`, but it's not pretty (`hello/index.php?_url=/user`)

``` php
$di->set('url', function () {
    $url = new \Ice\Mvc\Url();
    $url->setBaseUri('/index.php?_url=/');

    return $url;
});
```

**Comment by mcddx330** [comment]
I challenged on h2o, but doesn't work it...
Base url setting is worked. but yes, it is not pretty.
So i will use with nginx. thanks for helping :)
