### ISSUE TITLE
Problem with controller directory

### ISSUE THREAD

**Issue by sayonara90s** [ice/framework#127]
Handler Class with application/Controllers/ doesn't work.

```
ice-php/
.. application/
.. .. Controllers/
.. .. ..
```

Any idea?

I think this framework so simple than Phalcon but need more documentation like Bootstrap, Routing, Controller, Models, and other basics. And I have'nt found forum.

Sorry for My English, thanks!

**Comment by mruz** [comment]
For the psr-4 try to change directory to _ice-php/Application/Controller_.

Also did you follow https://www.iceframework.org/doc/tutorial/hello first?

**Comment by sayonara90s** [comment]
Yes. Handler class works with application/Controller/, not /Controllers/ (I'm using this for my Phalcon project).

I will clone ice/website repo for more info.
Thank you for your fast response.

**Comment by mruz** [comment]
You can also set default namespace:
$di->dispatcher->setDefaultNamespace('Application\Controllers');

**Comment by sayonara90s** [comment]
Beuh, I forgot something. :) Thank you.
