### ISSUE TITLE
 Unable to load dynamic library '/usr/lib64/php/modules/ice.so'

### ISSUE THREAD

**Issue by xuzhenjun130** [ice/framework#144]
help!

`
Starting php-fpm: [24-Feb-2017 09:42:45] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/ice.so' - /usr/lib64/php/modules/ice.so: undefined symbol: php_json_decode_ex in Unknown on line 0
`

PHP Version 7.0.16
centos6.3

**Comment by xuzhenjun130** [comment]
phalcon  is ok!

**Comment by mruz** [comment]
You have to use the json extension before ice.
Depending how you activated ice, move `extension=ice.so` below json or rename `/etc/php7/conf.d/ice.ini` to  eg. `/etc/php7/conf.d/zephir_ice.ini`
