### ISSUE TITLE
Can this framework support Oracle database？

### ISSUE THREAD

**Issue by e4x** [ice/framework#150]
I tried to use ice，and set oracle as project's database, it not work,Is this framework not support Oracle?

`
$di->set('db', function () {
    $tns = '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=orcl)))';
    $driver = new \Ice\Db\Driver\Pdo("oracle:dbname=" . $tns, 'user', 'password');
//    not work too
//    $driver = new \Ice\Db\Driver\Pdo("oci:dbname=orcl;host=localhost", 'user', 'password');

    return new \Ice\Db($driver);
});
`

**Comment by mruz** [comment]
It's supported by PDO, so it should work,

Could you please try:
```
$di->set('db', function () {
    $driver = new \Ice\Db\Driver\Pdo('oci:host=localhost;port=1521;dbname=orcl', 'user', 'pass');
    return new \Ice\Db($driver);
```

**Comment by e4x** [comment]
@mruz  as you said, it's work, but it must be this:

`
$di->set('db', function () {
$tns = '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=orcl)))';
$driver = new \Ice\Db\Driver\Pdo("oci:dbname=" . $tns, 'user', 'password');
`

your code will throw a oracle ORA-12154 error

Thanks a lot!
