### ISSUE TITLE
Long time no precompilled dll library

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#152]
would u plz update the `php_ice.dll` to the latest version?

thanks for so great framework

**Comment by mruz** [comment]
OK, I'll try to find windows machine and generate dll. [Build on Windows](https://www.iceframework.org/doc/introduction/windows).

**Comment by mruz** [comment]
I added DLLs for PHP 7.2 [Download Ice Framework](https://www.iceframework.org/info/download).

**Comment by mruz** [comment]
Now we're on [pecl](https://pecl.php.net/package/ice), so dlls are generated automatically.
