### ISSUE TITLE
Unable to load dynamic library '/usr/lib64/php/modules/ice.so'

### ISSUE THREAD

**Issue by legolass73** [ice/framework#153]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/ice.so' - /usr/lib64/php/modules/ice.so: undefined symbol: zval_used_for_init in Unknown on line 0
include_path => .:/usr/share/pear:/usr/share/php => .:/usr/share/pear:/usr/share/php

php version 7.1.21
Centos 7.5

**Comment by mruz** [comment]
https://github.com/phalcon/zephir/issues/1327
I will try to regenerate with the latest zephir.

**Comment by mruz** [comment]
@legolass73 could you try with latest build? #164

**Comment by legolass73** [comment]
Yes, but in the end I dropped out.
Cordialement,
Stefan. Servais.



Le sam. 8 sept. 2018 à 17:51, Mariusz Łączak <notifications@github.com> a
écrit :
