### ISSUE TITLE
loader addNamespace bug

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#154]
`$loader->addNamespace('', __DIR__ . '/Vendor/Parsedown')` 
or `$loader->addNamespace('/', __DIR__ . '/Vendor/Parsedown')` 
or `$loader->addNamespace("\\", __DIR__ . '/Vendor/Parsedown')` 
doesn't work for `Parsedown` class dropped in `__DIR__ . '/Vendor/Parsedown'` directory.

$mk = new Parsedown; // class not found

please fix [line 78](https://github.com/ice/framework/blob/dev/ice/loader.zep#L78)，these is no `\` in the class name

**Comment by mruz** [comment]
Loader uses https://www.php-fig.org/psr/psr-4 and example implementation from there. 
How about if you add e.g. `Vendor` namespace?
```
use Vendor/Parsedown/Parsedown;
...
$mk = new Parsedown; 
```

**Comment by Yahasana** [comment]
there is no `Parsedown` namespace. Loader should support to load class without namespace.

vendor directory stores 3rd-part libs. it's bad to touch them and add extra `Vendor/***` namespace

**Comment by Yahasana** [comment]
Limitations for psr-4 are not good for old style 3rd-party libs:
> A fully qualified class name has the following form:

 \<NamespaceName>(\<SubNamespaceNames>)*\<ClassName>

    The fully qualified class name MUST have a top-level namespace name,
    also known as a “vendor namespace”.

    The fully qualified class name MAY have one or more sub-namespace
    names.

**Comment by Yahasana** [comment]
Take an eye at loader implement in Phalcon. it allows to add any kinds of directories to the loader. powerful but complicated.

**Comment by mruz** [comment]
OK, I'll take a look. Usually I'm adding the composer's autoloader too https://github.com/ice/base/blob/master/public/index.php#L15 and use Ice\Loader for psr-4 only.
```php
<?php
// Register App namespace
$loader = new Ice\Loader();
$loader
    ->addNamespace('App', __DIR__ . '/App')
    ->register();
// Include composer's autolader
$composer = include_once __DIR__ . '/vendor/autoload.php';
return $loader;
```

**Comment by Yahasana** [comment]
So, how to add class without a composer repos? `autoload.php` maintained by composer and bad practice to change it by hand too.
