### ISSUE TITLE
Pass di when register module autoloaders

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#156]
it'll be very convenient to access DI instance when `ModuleInterface::registerAutoloaders()` is changed to `ModuleInterface::registerAutoloaders(variable $di) `.

```php
    public function registerAutoloaders()
    {
        (new Loader())
            ->addNamespace(__NAMESPACE__ . '\Controllers', __DIR__ . '/controllers/')
            ->register();
    }
```
VS

```php
    // better performance
    public function registerAutoloaders(Di $di)
    {
        $di->loader->addNamespace(__NAMESPACE__ . '\Controllers', __DIR__ . '/controllers/');
    }
```

**Comment by Yahasana** [comment]
an amazing feature that allow user to set a higher loading order for the current module when prepend the loading namespaces: `$di->loader->addNamespace(__NAMESPACE__ . '\Controllers', __DIR__ . '/controllers/', true);`

**Comment by mruz** [comment]
It's easy to  implement, how about `$di = null` by default, to keep backward compatibility?
https://github.com/ice/framework/blob/dev/ice/dispatcher.zep#L189
https://github.com/ice/framework/blob/dev/ice/mvc/moduleinterface.zep#L18

**Comment by Yahasana** [comment]
@mruz it's fine!

**Comment by Yahasana** [comment]
After a sound thought, pass [the loader](https://github.com/ice/framework/blob/dev/ice/dispatcher.zep#L182) loading the current module to `registerAutoloaders($loader)` to allow developer control the module loading process. 

if people want to access the `$di` instance, it can be done in `registerServices(Di $di)`

BTW, add `Loader $loader = null` to `ModuleInterface::registerAutoloaders(Loader $loader = null)` doesn't keep backward compatibility. So, `ModuleInterface::registerAutoloaders(Loader $loader)` is ok

**Comment by Yahasana** [comment]
@mruz please check my last comment. the follow code will not work as expect, as the loader of the module is not the same as the one in `$di->loader`. it safe to pass `$loader` but not `this->di`.
```php
    // better performance
    public function registerAutoloaders(Di $di)
    {
        $di->loader->addNamespace(__NAMESPACE__ . '\Controllers', __DIR__ . '/controllers/');
    }
```

**Comment by mruz** [comment]
I didn't see your comment.

**Comment by mruz** [comment]
```
let loader = this->di->get("loader")
```
Will get the loader from te di or create a new if not exist, so maybe that way.
Then `ModuleInterface::registerAutoloaders(Loader $loader = null)`, you won't need to update your app if you have just `registerAutoloaders()` in every module.

**Comment by Yahasana** [comment]
Every loader has its own namespaces room. create a new loader to load a module to guarantee its independent room and don't pollute the global loader (`this->di->get('loader')`) . 
How do you think?
