### ISSUE TITLE
How to render out fatal errors

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#157]
Sorry for this simple question. how can i setup to output when there are fatal errors happen. I got a blank page at this moment.

**Comment by Yahasana** [comment]
solved
```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by mruz** [comment]
Cool, you could also call `$di->errors();` to handle errors by Ice\Exception.
https://github.com/ice/framework/blob/dev/ice/di.zep#L255
