### ISSUE TITLE
add db::query($sql, $filter, $options)

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#166]
I found there is [Q&A](https://github.com/ice/framework/issues/101) for this feature. it'd be fine to add a helper method to run native sql

**Comment by mruz** [comment]
Ice\Db is a database component for both slq and nosql, so `db::query($sql, ...` is not good place to add query only for sql. Drivers (pdo and mongodb) are for simple queries, they share the same syntax: 
```
      //SELECT FROM users WHERE a=1 and b="q"
      $db->find("users", ["a" => 1, "b" => "q"]);
     
      //SELECT FROM users WHERE age>33 
      $db->find("users", ["age" => [">" => 33]]);
     
      //SELECT FROM users WHERE a=1 or b=2 
      $db->find("users", ["OR" => [["a" => 1], ["b" => 2]]]);
```
If you want to run complex sql queries, I suggest to call `getClient()` to get native php [Pdo](http://pl1.php.net/manual/en/class.pdo.php) class.

PS. Look also at the [Model](https://www.iceframework.org/doc/component/model).

**Comment by Yahasana** [comment]
there are `query` feature for both sql or [nosql](https://docs.mongodb.com/manual/tutorial/query-documents/). it can run sql string for sql driver (PDO) or find json object for nosql driver. both return the result without populate to kind of model

**Comment by mruz** [comment]
https://github.com/ice/framework/pull/204
