### ISSUE TITLE
route with extension

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#195]
How to setup a common route to match `/module/controller/action/id/param.json`

**Comment by mruz** [comment]
How about?
```

            ['*', '/{module:[a-z-]+}[/{controller:[a-z-]+}[/{action:[a-z-]+}[/{id}[/{param}]]]]'],
```

**Comment by Yahasana** [comment]
not works. this rule can't match `.json`

**Comment by mruz** [comment]
try `[/{param:[a-z\.]+}]`

**Comment by Yahasana** [comment]
`['*', '/{module:[a-z-]+}[/{controller:[a-z-]+}[/{action:[a-z-]+}[/{id}[/{param}]]]]']`

DON"T WORK: http://e.com/account/user/signup/id.json

WORK: http://e.com/account/user/signup/id/a.json
```php
public function signupAction() {
    print_r(func_get_args());
}
Array
(
    [0] => id
    [1] => a
    [2] => json
)
```
WORK: http://e.com/account/user/signup/id/a/b.json
```php
public function signupAction() {
    print_r(func_get_args());
}
Array
(
    [0] => id/a             <---------- what's wrong?
    [1] => b
    [2] => json
)
```

**Comment by Yahasana** [comment]
abandon fastroute & close
