### ISSUE TITLE
Good look exception report

### ISSUE THREAD

**Issue by Yahasana** [ice/framework#234]
![image](https://user-images.githubusercontent.com/97450/46845809-a1d93c80-ce0f-11e8-8ee6-6ef8d4968d48.png)

**Comment by mruz** [comment]
I like that one. I use dump to display it https://github.com/ice/base/blob/master/App/Boot/Error.php, but we could have it in the Exception. Maybe add a callback to run some code after Exception, like send email, display a view with a generic message if environment is production and pretty print if environment is development.
We could use cssmin to send the styles straight from the Exception.
Have you tried https://github.com/filp/whoops?

**Comment by Yahasana** [comment]
whoops look cute but there is no `arguments` info and the stack frames panel distract my attention. I like the KISS rule

**Comment by mruz** [comment]
It will be possible to apply some hook and overwrite the response on exception, e.g. set content from custom view with assets
![exception](https://user-images.githubusercontent.com/2629882/47412371-805b4780-d763-11e8-83d6-6bacec1352e4.png)

**Comment by mruz** [comment]
I'll add a tutorial to the documentation with some example.
