### ISSUE TITLE
Sleet

### ISSUE THREAD

**Issue by ezequieltomazini** [ice/framework#278]
Hello,
where do I find the view (sleet) documentation to find out which filters / functions?
Do they have the same features as VOlt / Twig?

**Comment by mruz** [comment]
Unfortunately they are not documented yet. They have similar features to volt/twig.

Functions:
View: content, partial, load, 
General: dump, version,
Tag: text_field, password_field, hidden_field, submit_button, button, check_field, radio_field, input, form, end_form, text_area, image, img, link_to, a, link, script, style, select, tag_html, end_tag, friendly_title, get_doc_type, get_title, get_meta

Filters:
capitalize, camelize, uncamelize, human, lower, upper, alnum, alpha, email, float, int, string, strip_repeats, e, escape, strip_special, unescape, unstrip_special

https://github.com/ice/framework/blob/dev/ice/mvc/view/engine/sleet/parser.zep

PS.
You can also use all build in php functions as filters `title|isset` but functions with multiple parameters are not supported well.

**Comment by ezequieltomazini** [comment]
Thank you Mariusz.

Will Ice continue to be maintained and as an extension? I currently use phalcon in several projects, but it will be discontinued as an extension, so I intend to migrate to ICE.

**Comment by mruz** [comment]
Yes, no plan to drop it and I hope we will add support for php8 soon https://github.com/phalcon/zephir/issues/2111.
I need to improve our [documentation](https://www.iceframework.org/doc), for now you can check our [api](https://doc.iceframework.org).
