### ISSUE TITLE
Install ice via composer instead of pecl

### ISSUE THREAD

**Issue by waghanza** [ice/framework#300]
Hi,

Following https://github.com/dependabot/dependabot-core/issues/1990, you meqan @mruz that `composer`, with
```json
{
  "require": {
    "iceframework/framework": "~1.8.0"
  }
}
```
could handle `ice` compilation

That's not what I have using `composer install --no-dev --prefer-dist --classmap-authoritative` (I'm using https://github.com/the-benchmarker/web-frameworks to try this).

Regards,

**Comment by mruz** [comment]
> Note: Only scripts defined in the root package's composer.json are executed. If a dependency of the root package specifies its own scripts, Composer does not execute those additional scripts. -https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-


You would need to define a script which calls ice's script:
```json
{
  "require": {
    "iceframework/framework": "~1.8.0"
  },
  "scripts": {
    "post-install-cmd": [
      "cd vendor/iceframework/framework && ./install"
    ]
  }
}
```

**Comment by waghanza** [comment]
could / should not it be defined by ice's composer.json ? @mruz

**Comment by mruz** [comment]
It is defined, but composer does not execute those additional scripts from packages, only from root.
