### ISSUE TITLE
Model unserialize Exception

### ISSUE THREAD

**Issue by mruz** [ice/framework#37]
I'm getting error exception after sign in with _remember me_ option:

> ErrorException[8]: unserialize(): Error at offset 0 of 34 bytes

It occurs on one app, but not with another. Looks like error with [fcache](https://github.com/phalcon/zephir/issues/715) (works before this commit) or zephir latest changes.

Strange trace:

```
#0 [internal function]: unserialize('Ice\\Auth\\Driver\\Model\\Users\\Tokens')
#1 [internal function]: Ice\Mvc\Model->unserialize('Ice\\Auth\\Driver\\Model\\Users\\Tokens')
```

```
#0 [internal function]: unserialize('echo')
#1 [internal function]: Ice\Mvc\Model->unserialize('echo')
```

```
#0 [internal function]: unserialize('1\x00\x00\x00\x00\x00\x00\x001\x00\x00\x00\x00\x00\x00')
#1 [internal function]: Ice\Mvc\Model->unserialize(Array)
#2 [internal function]: Ice\Auth\Driver\Model->getUser()
```

It may be related with the [crypt.zep#L100](https://github.com/ice/framework/blob/9e603f5a9feeebcc023ed2fc0725d43c6d359779/ice/crypt.zep#L100), because [auth/driver/model.zep#L185](https://github.com/ice/framework/blob/9e603f5a9feeebcc023ed2fc0725d43c6d359779/ice/auth/driver/model.zep#L185) launches [cookies.zep#L102](https://github.com/ice/framework/blob/9e603f5a9feeebcc023ed2fc0725d43c6d359779/ice/cookies.zep#L102) during _remember me_ option. Auth and Crypt uses unserialize function but with diferent data.

If I change serialize/unserialize to json_encode/json_decode in the [mvc/model.zep#L622](https://github.com/ice/framework/blob/9e603f5a9feeebcc023ed2fc0725d43c6d359779/ice/mvc/model.zep#L622) or disable cookies encrypt it works. I'm trying to add code to reproduce this issue.

**Comment by mruz** [comment]
@steffengy @ovr could you look at the fcache again?

**Comment by steffengy** [comment]
@mruz Have you pinpointed the exact commit breaking iit? 
I will probably take a look at it soon :)

**Comment by mruz** [comment]
On the https://github.com/phalcon/zephir/commit/9b55e6a8c1d87c9367d06c9a4260c7097978474e  works. On the next commit (enable function cache) https://github.com/phalcon/zephir/commit/e1a78ce707b408d1ce80740890478aef56a764ad  SIGSEGV signal.

It began working on https://github.com/phalcon/zephir/commit/ec91835685c79bee4c4b7fe94bbdfee91ff354e5 but this issue occurs. Also with the latest commit https://github.com/phalcon/zephir/commit/bd10250474c8d75a5bf72aebd92fd74f1579159f

**Comment by steffengy** [comment]
@mruz 
Ok, it would be nice if you could produce a small testcase so that I do not have to setup ice framework again, If you can't produce one, I don't quite know yet, when I'll have the time to set that stuff up again & test it (because it's pretty time consuming that way)

**Comment by mruz** [comment]
Issue with `unserialize` is back after update to the latest Zephir.

**Comment by steffengy** [comment]
Can you pinpoint the commit breaking it?
Also do you have code to reproduce?

**Comment by mruz** [comment]
This happens on a production machine. I'm trying to reproduce on the local.

**Comment by mruz** [comment]
@steffengy I reproduced the issue on the local machine, but its hard to share code to reproduce.

Before phalcon/zephir/pull/831, phalcon/zephir/pull/831 it works, after https://github.com/phalcon/zephir/commit/5680acfb95d269022295c7e96eb2db6c28cf20d9 it looks like calling unserialize twice in my environment takes semi-random data from memory.

**Comment by steffengy** [comment]
This seems to be rather complex.
I will try to take a look at this,
it's probably some kind of optimizer fail.
(Memory getting garbage collected I guess)
Do you use any of the optimized calls before calling unserialize? Maybe on the same data?

Will try to look into it after I'm home.

**Comment by mruz** [comment]
Before unserialize in the crypt _stripPadding_ https://github.com/ice/framework/blob/dev/ice/crypt.zep#L175 is runned. Maybe here is a problem.

**Comment by steffengy** [comment]
::decrypt works just fine locally...
So I guess I'm having troubles reproducing, probably some
kind of edge-case.

I'm pretty sure it isn't fcache this time though...

**Comment by mruz** [comment]
It seems that with the latest zephir works fine.
