### ISSUE TITLE
What's the story on this vs phalcon?

### ISSUE THREAD

**Issue by brandonlamb** [ice/framework#62]
Hello,

Don't see a forum or whatever to post this question.

I'm just curious about what is the story with this framework? Is it a fork of phalcon, completely new but using zephir, etc?

I know there are threads regarding the slow progress, lack of PR merges and that kind of thing and people wanting cphalcon to move to an organization. Is that the reason or intent behind ice?

Thanks!

**Comment by mruz** [comment]
I really like Phalcon, but I don't like a lots of not reviewed pull requests (you need to check yourself if something has already been fixed and hangs in PR), lots of not closed issues, insistence on backward compatibility, the process of releasing version. I contributed with phalcon 2.0 [cphalcon/mruz's pulls](https://github.com/phalcon/cphalcon/pulls?q=is%3Apr+author%3Amruz+is%3Aclosed) and I really like Zephir.

I needed to create a simple and fast app for own use, but I decided to make small framework and make it public. Framework written from scratch, some components works like Phalcon's. Ice also has some cool new functionality.

This is just the beginning, so there is no forum, you can ask questions here.

**Comment by brandonlamb** [comment]
Cool, thanks for info!

**Comment by ezequieltomazini** [comment]
Hello,
where do I find the view (sleet) documentation to find out which filters / functions
