### ISSUE TITLE
Precompilled dll library

### ISSUE THREAD

**Issue by zaksmok** [ice/framework#92]
Is there any chance to share compiled DLLs of this extension for windows users?

**Comment by mruz** [comment]
I'm not a windows user, but I'll try to prepare dll's. There is a tutorials how to do it:
https://wiki.php.net/internals/windows/stepbystepbuild

http://phalconphp-internals-documentation.readthedocs.org/en/latest/reference/compilation.html
http://szdredd.blogspot.cz/2013/11/how-to-setup-phalcon-framework-under.html
Just to change `phalcon` to `ice`.

**Comment by mruz** [comment]
I added `dlls` to [Download](http://www.iceframework.org/info/download) and [Building instruction](http://website/doc/introduction/windows).
